# GENERAL CONFIGURATION
task: detection
output_dir: ./outputs/deim_hgnetv2_n
config: DEIM/configs/deim_dfine/deim_hgnetv2_n_coco.yml
__include__: [DEIM/configs/deim_dfine/dfine_hgnetv2_n_coco.yml, DEIM/configs/base/deim.yml]
seed: null
test_only: false
print_method: builtin
print_rank: 0
print_freq: 100
checkpoint_freq: 4
num_classes: 4
remap_mscoco_category: false

# MODEL ARCHITECTURE
model: DEIM
criterion: DEIMCriterion
postprocessor: PostProcessor
use_focal_loss: true
eval_spatial_size: [640, 640]

# BACKBONE CONFIGURATION
HGNetv2:
  pretrained: true
  local_model_dir: RT-DETR-main/D-FINE/weight/hgnetv2/
  name: B0
  return_idx: [2, 3]
  freeze_at: -1
  freeze_norm: false
  use_lab: true

# ENCODER CONFIGURATION
HybridEncoder:
  in_channels: [512, 1024]
  feat_strides: [16, 32]
  hidden_dim: 128
  use_encoder_idx: [1]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 512
  dropout: 0.0
  enc_act: gelu
  expansion: 0.34
  depth_mult: 0.5
  act: silu

# DECODER CONFIGURATION
DFINETransformer:
  feat_channels: [128, 128]
  feat_strides: [16, 32]
  hidden_dim: 128
  num_levels: 2
  num_layers: 3
  eval_idx: -1
  num_queries: 300
  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0
  reg_max: 32
  reg_scale: 4
  layer_scale: 1
  num_points: [6, 6]
  cross_attn_method: default
  query_select_method: default
  dim_feedforward: 512
  activation: silu
  mlp_act: silu

# POST-PROCESSING
PostProcessor:
  num_top_queries: 300

# LOSS CONFIGURATION
DEIMCriterion:
  weight_dict:
    loss_vfl: 1
    loss_bbox: 5
    loss_giou: 2
    loss_fgl: 0.15
    loss_ddf: 1.5
    loss_mal: 1
  losses: [mal, boxes, local]
  alpha: 0.75
  gamma: 1.5
  reg_max: 32
  matcher:
    type: HungarianMatcher
    weight_dict:
      cost_class: 2
      cost_bbox: 5
      cost_giou: 2
    alpha: 0.25
    gamma: 2.0

# TRAINING CONFIGURATION
epoches: 30
clip_max_norm: 0.1
sync_bn: true
find_unused_parameters: false
use_amp: true
use_ema: true
lrsheduler: flatcosine
lr_gamma: 0.1
warmup_iter: 200
flat_epoch: 15
no_aug_epoch: 3

# OPTIMIZER SETTINGS
optimizer:
  type: AdamW
  params:
    - params: "^(?=.*backbone)(?!.*bn).*$"
      lr: 0.0005
    - params: "^(?=.*(?:norm|bn)).*$"
      weight_decay: 0.0
  lr: 0.0004
  betas: [0.9, 0.999]
  weight_decay: 0.0001

# LEARNING RATE SCHEDULING
lr_scheduler:
  type: MultiStepLR
  milestones: [30]
  gamma: 0.1

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 50

# AMP SCALER
scaler:
  type: GradScaler
  enabled: true

# EMA CONFIGURATION
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 200
  start: 0

# EVALUATION
evaluator:
  type: CocoEvaluator
  iou_types: [bbox]

# TRAINING DATALOADER
train_dataloader:
  type: DataLoader
  shuffle: true
  num_workers: 4
  drop_last: true
  total_batch_size: 32
  dataset:
    type: CocoDetection
    img_folder: /home/dnth/Downloads/rock_paper_scissors/train
    ann_file: /home/dnth/Downloads/rock_paper_scissors/train/_annotations.coco.json
    return_masks: false
    transforms:
      type: Compose
      ops:
        - type: Mosaic
          output_size: 320
          rotation_range: 10
          translation_range: [0.1, 0.1]
          scaling_range: [0.5, 1.5]
          probability: 1.0
          fill_value: 0
          use_cache: false
          max_cached_images: 50
          random_pop: true
        - type: RandomPhotometricDistort
          p: 0.5
        - type: RandomZoomOut
          fill: 0
        - type: RandomIoUCrop
          p: 0.8
        - type: SanitizeBoundingBoxes
          min_size: 1
        - type: RandomHorizontalFlip
        - type: Resize
          size: [640, 640]
        - type: SanitizeBoundingBoxes
          min_size: 1
        - type: ConvertPILImage
          dtype: float32
          scale: true
        - type: ConvertBoxes
          fmt: cxcywh
          normalize: true
      policy:
        name: stop_epoch
        epoch: [4, 30, 50]
        ops:
          - Mosaic
          - RandomPhotometricDistort
          - RandomZoomOut
          - RandomIoUCrop
      mosaic_prob: 0.5
  collate_fn:
    type: BatchImageCollateFunction
    base_size: 640
    base_size_repeat: 20
    stop_epoch: 45
    ema_restart_decay: 0.9999
    mixup_prob: 0.5
    mixup_epochs: [4, 45]

# VALIDATION DATALOADER
val_dataloader:
  type: DataLoader
  shuffle: false
  num_workers: 4
  drop_last: false
  total_batch_size: 16
  dataset:
    type: CocoDetection
    img_folder: /home/dnth/Downloads/rock_paper_scissors/valid
    ann_file: /home/dnth/Downloads/rock_paper_scissors/valid/_annotations.coco.json
    return_masks: false
    transforms:
      type: Compose
      ops:
        - type: Resize
          size: [640, 640]
        - type: ConvertPILImage
          dtype: float32
          scale: true
  collate_fn:
    type: BatchImageCollateFunction