task: detection
_model: null
_postprocessor: null
_criterion: null
_optimizer: null
_lr_scheduler: null
_lr_warmup_scheduler: null
_train_dataloader: null
_val_dataloader: null
_ema: null
_scaler: null
_train_dataset: null
_val_dataset: null
_collate_fn: null
_evaluator: null
_writer: null
num_workers: 0
batch_size: null
_train_batch_size: null
_val_batch_size: null
_train_shuffle: null
_val_shuffle: null
resume: null
tuning: null
epoches: 160
last_epoch: -1
lrsheduler: flatcosine
lr_gamma: 0.5
no_aug_epoch: 12
warmup_iter: 20
flat_epoch: 78
use_amp: true
use_ema: true
ema_decay: 0.9999
ema_warmups: 20
sync_bn: true
clip_max_norm: 0.1
find_unused_parameters: false
seed: 0
print_freq: 100
checkpoint_freq: 4
output_dir: ./outputs/deim_hgnetv2_n
summary_dir: null
device: ""
yaml_cfg:
  task: detection
  evaluator:
    type: CocoEvaluator
    iou_types: [bbox]
  num_classes: 4
  remap_mscoco_category: false
  train_dataloader:
    type: DataLoader
    dataset:
      type: CocoDetection
      img_folder: /home/dnth/Desktop/DEIM/dataset/images/train
      ann_file: /home/dnth/Desktop/DEIM/dataset/images/annotations/instances_train.json
      return_masks: false
      transforms:
        type: Compose
        ops:
          - type: Mosaic
            output_size: 320
            rotation_range: 10
            translation_range: [0.1, 0.1]
            scaling_range: [0.5, 1.5]
            probability: 1.0
            fill_value: 0
            use_cache: false
            max_cached_images: 50
            random_pop: true
          - type: RandomPhotometricDistort
            p: 0.5
          - type: RandomZoomOut
            fill: 0
          - type: RandomIoUCrop
            p: 0.8
          - type: SanitizeBoundingBoxes
            min_size: 1
          - type: RandomHorizontalFlip
          - type: Resize
            size: [640, 640]
          - type: SanitizeBoundingBoxes
            min_size: 1
          - type: ConvertPILImage
            dtype: float32
            scale: true
          - type: ConvertBoxes
            fmt: cxcywh
            normalize: true
        policy:
          name: stop_epoch
          epoch: [4, 78, 148]
          ops:
            - Mosaic
            - RandomPhotometricDistort
            - RandomZoomOut
            - RandomIoUCrop
        mosaic_prob: 0.5
    shuffle: true
    num_workers: 4
    drop_last: true
    collate_fn:
      type: BatchImageCollateFunction
      base_size: 640
      base_size_repeat: 20
      stop_epoch: 148
      ema_restart_decay: 0.9999
      mixup_prob: 0.5
      mixup_epochs: [4, 78]
    total_batch_size: 32
  val_dataloader:
    type: DataLoader
    dataset:
      type: CocoDetection
      img_folder: /home/dnth/Desktop/DEIM/dataset/images/valid
      ann_file: /home/dnth/Desktop/DEIM/dataset/images/annotations/instances_val.json
      return_masks: false
      transforms:
        type: Compose
        ops:
          - type: Resize
            size: [640, 640]
          - type: ConvertPILImage
            dtype: float32
            scale: true
    shuffle: false
    num_workers: 4
    drop_last: false
    collate_fn:
      type: BatchImageCollateFunction
    total_batch_size: 16
  print_freq: 100
  output_dir: ./outputs/deim_hgnetv2_n
  checkpoint_freq: 4
  sync_bn: true
  find_unused_parameters: false
  use_amp: true
  scaler:
    type: GradScaler
    enabled: true
  use_ema: true
  ema:
    type: ModelEMA
    decay: 0.9999
    warmups: 1000
    start: 0
  epoches: 160
  clip_max_norm: 0.1
  optimizer:
    type: AdamW
    params:
      - params: "^(?=.*backbone)(?!.*bn).*$"
        lr: 0.0002
      - params: "^(?=.*(?:norm|bn)).*$"
        weight_decay: 0.0
    lr: 0.0004
    betas: [0.9, 0.999]
    weight_decay: 0.0001
  lr_scheduler:
    type: MultiStepLR
    milestones: [500]
    gamma: 0.1
  lr_warmup_scheduler:
    type: LinearWarmup
    warmup_duration: 500
  model: DEIM
  criterion: DEIMCriterion
  postprocessor: PostProcessor
  use_focal_loss: true
  eval_spatial_size: [640, 640]
  DEIM:
    backbone: HGNetv2
    encoder: HybridEncoder
    decoder: DFINETransformer
  lrsheduler: flatcosine
  lr_gamma: 0.5
  warmup_iter: 20
  flat_epoch: 78
  no_aug_epoch: 12
  HGNetv2:
    pretrained: true
    local_model_dir: RT-DETR-main/D-FINE/weight/hgnetv2/
    name: B0
    return_idx: [2, 3]
    freeze_at: -1
    freeze_norm: false
    use_lab: true
  HybridEncoder:
    in_channels: [512, 1024]
    feat_strides: [16, 32]
    hidden_dim: 128
    use_encoder_idx: [1]
    num_encoder_layers: 1
    nhead: 8
    dim_feedforward: 512
    dropout: 0.0
    enc_act: gelu
    expansion: 0.34
    depth_mult: 0.5
    act: silu
  DFINETransformer:
    feat_channels: [128, 128]
    feat_strides: [16, 32]
    hidden_dim: 128
    num_levels: 2
    num_layers: 3
    eval_idx: -1
    num_queries: 300
    num_denoising: 100
    label_noise_ratio: 0.5
    box_noise_scale: 1.0
    reg_max: 32
    reg_scale: 4
    layer_scale: 1
    num_points: [6, 6]
    cross_attn_method: default
    query_select_method: default
    dim_feedforward: 512
    activation: silu
    mlp_act: silu
  PostProcessor:
    num_top_queries: 300
  DEIMCriterion:
    weight_dict:
      loss_vfl: 1
      loss_bbox: 5
      loss_giou: 2
      loss_fgl: 0.15
      loss_ddf: 1.5
      loss_mal: 1
    losses: [mal, boxes, local]
    alpha: 0.75
    gamma: 1.5
    reg_max: 32
    matcher:
      type: HungarianMatcher
      weight_dict:
        cost_class: 2
        cost_bbox: 5
        cost_giou: 2
      alpha: 0.25
      gamma: 2.0
  __include__: [DEIM/configs/deim_dfine/dfine_hgnetv2_n_coco.yml, DEIM/configs/base/deim.yml]
  config: DEIM/configs/deim_dfine/deim_hgnetv2_n_coco.yml
  seed: 0
  test_only: false
  print_method: builtin
  print_rank: 0